
version: '3.7'

services:

  myapp:
    build: .
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=IaFest
      - MYSQL_PASSWORD=I123Af
      - MYSQL_DATABASE=Covid
    volumes:
      - .:/app
    ports:
      - 5000:5000
    links:
      - mysql



  mysql:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: <ROOT_PASSWORD>
      MYSQL_DATABASE: Covid
      MYSQL_USER: IaFest
      MYSQL_PASSWORD: I123Af
    ports:
      - 3306:3306

